# Generated by Django 6.0.1 on 2026-05-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLHandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickevent',
            name='visitor_id',
        ),
    ]
