# Generated by Django 6.0.1 on 2026-05-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLHandler', '0002_remove_clickevent_visitor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
