# Generated by Django 6.0.1 on 2026-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLHandler', '0003_alter_shorturl_shortquery_alter_shorturl_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
